### ISSUE TITLE
Consider removing .env file

### ISSUE THREAD

**Issue by jdrago999** [tophfr/docker-mailcatcher#3]
It's not clear where the .env file is used -- not in docker-compose.yml, not referenced in the README.md and not used in the Dockerfile.

Was it mistakenly added?

**Comment by tophfr** [comment]
Hello
my `docker-compose.yml` here requires that the `VERSION` env var is defined
the `.env` file is used when you run `docker-compose` from the same path
if you need to build or run with another value and don't want to modify a commited file you can do something like this :
```
VERSION=0.6.4 docker-compose build
```
Thx
